apiVersion: v1
kind: Namespace
metadata:
  name: knote-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
  namespace: knote-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: knote-java:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: MINIO_ACCESS_KEY
              value: mykey
            - name: MINIO_SECRET_KEY
              value: mysecret
            - name: MINIO_HOST
              value: minio
          imagePullPolicy: Never
---

apiVersion: v1
kind: Service
metadata:
  name: knote
  namespace: knote-test
spec:
  selector:
    app: knote
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
